### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by neonightmare** [MoritzBuetzer/homeassistant-vzug#1]
Hi Moritz

I would like to integrate my V-Zug into Home-Assistant, how far is your implementation?
maybe you could integrate it in HACS? [https://hacs.xyz/](url)

THX Neo

**Comment by MoritzBuetzer** [comment]
Hi Neo

Thanks you for asking. Unfortunately i have done nothing more so far except the [python-vzug](https://github.com/MoritzBuetzer/python-vzug) base api. I don't think it should be a big effort, but honestly, i don't know if i'll work on it any more in the near future. At the moment, all my V-Zug appliances are connected with the REST-Platform in Home Assistant. [I've made a small example](https://gist.github.com/MoritzBuetzer/6441d4045f989ef57aed915250bb4020).

And yes, HACS would definitely be preferred.

Moritz
